Merged PR 123991: EL2 Mem Interface modports, new double-bit error injection testcase, fix for UVM edge case
Use modports at every port connection point for the EL2 Mem export interface, which resolves https://github.com/chipsalliance/caliptra-rtl/issues/179

Add a new UVM testcase that injects double bit errors into the Mailbox SRAM during a mailbox flow operation and checks the response

Fix for an edge case in a UVM test where response data size (communicated through in-band data payload) is corrupted as part of an error injection test in the uvmf_soc_ifc suite.

Related work items: #519675

diff --git a/tools/scripts/run_test_makefile b/tools/scripts/run_test_makefile
--- a/tools/scripts/run_test_makefile
+++ b/tools/scripts/run_test_makefile
@@ -54,8 +54,16 @@ fi
 
 #remove random SEED from TESTNAME after "__" characters
 baseTestName=$(echo "$TESTNAME" | sed 's/\__.*//')
+seed=$( echo "$TESTNAME" | sed 's/.*__//')
+if [[ ( -z ${seed:+"empty"} ) || ( ${seed} == ${TESTNAME} ) ]]; then
+    seed=${PLAYBOOK_RANDOM_SEED}
+fi
+if [[ -z ${seed:+"empty"} ]]; then
+    echo "Failed to populate the randomization seed during FW build!"
+    exit 1
+fi
 
-echo "[$SCRIPT] Building TEST=$baseTestName from TESTNAME=$TESTNAME for CONFIG=${CONFIG}"
+echo "[$SCRIPT] Building TEST=$baseTestName from TESTNAME=$TESTNAME with SEED=$seed for CONFIG=${CONFIG}"
 export TESTNAME=$baseTestName
 
 # These bash functions cause the Makefile to not work, because it resets env vars and it chokes on the bash functions
@@ -65,7 +73,7 @@ unset -f _module_raw
 
 # This is the UVM-based ROM test
 if [[ $TESTNAME == "caliptra_top_rom_test" ]]; then
-    cmd="make -f $SCRIPTS_DIR/Makefile TESTNAME=fw_test_rom program.hex"
+    cmd="make -f $SCRIPTS_DIR/Makefile PLAYBOOK_RANDOM_SEED=$seed TESTNAME=fw_test_rom program.hex"
     echo "$cmd"
     $cmd
 # This is any other UVM-based test in caliptra_top bench
@@ -75,15 +83,15 @@ elif [[ ! -z $(echo $TESTNAME | grep -E "caliptra_top_\w*_test") ]]; then
     fi
     clean="make -f $SCRIPTS_DIR/Makefile clean_fw"
     echo "$clean"
-    cmd="make -f $SCRIPTS_DIR/Makefile TESTNAME=caliptra_top program.hex"
+    cmd="make -f $SCRIPTS_DIR/Makefile PLAYBOOK_RANDOM_SEED=$seed TESTNAME=caliptra_top program.hex"
     echo "$cmd"
     $clean
     $cmd
-    cmd="make -f $SCRIPTS_DIR/Makefile TESTNAME=caliptra_fmc caliptra_fmc.hex"
+    cmd="make -f $SCRIPTS_DIR/Makefile PLAYBOOK_RANDOM_SEED=$seed TESTNAME=caliptra_fmc caliptra_fmc.hex"
     echo "$cmd"
     $clean
     $cmd
-    cmd="make -f $SCRIPTS_DIR/Makefile BUILD_CFLAGS=$BUILD_CFLAGS TESTNAME=caliptra_rt  caliptra_rt.hex"
+    cmd="make -f $SCRIPTS_DIR/Makefile PLAYBOOK_RANDOM_SEED=$seed TESTNAME=caliptra_rt BUILD_CFLAGS=$BUILD_CFLAGS caliptra_rt.hex"
     echo "$cmd"
     $clean
     $cmd
