Merged PR 128855: [Bug fix] Mailbox rd_valid_f signal rst/init value; [UVM] validation fw fix for error intr handling
RTL fix:
- Add reset value for mbox_rd_valid_f, resolving a potential issue with mbox_dataout containing X values (resolves https://github.com/chipsalliance/caliptra-rtl/issues/250)

UVM Validation fix:
- Clear cmd_fail/inv_dev error interrupts at Mbox flow entry (val runtime firmware)

Related work items: #569091, #569460

diff --git a/tools/scripts/run_test_makefile b/tools/scripts/run_test_makefile
--- a/tools/scripts/run_test_makefile
+++ b/tools/scripts/run_test_makefile
@@ -60,11 +60,19 @@ fi
 
 #remove random SEED from TESTNAME after "__" characters
 baseTestName=$(echo "$TESTNAME" | sed 's/\__.*//')
-#seed=$( echo "$TESTNAME" | sed 's/.*__//')
-seed=$(eval echo $(grep -E '^seed:' ${TESTFILE} | sed 's,^seed: \([^# ]*\),\1,'))
+# First, try to extract the regression generated seed from the testname
+seed=$( echo "$TESTNAME" | sed 's/.*__//')
+# Second, if that fails, extract the run seed from the testfile pointed
+# to by sim_config.yml
+if [[ ( -z ${seed:+"empty"} ) || ( ${seed} == ${TESTNAME} ) ]]; then
+    seed=$(eval echo $(grep -E '^seed:' ${TESTFILE} | sed 's,^seed: \([^# ]*\),\1,'))
+fi
+# Third, if seed is still empty, use the environment variable (which,
+# in the default case, drives the VCS ntb_random_seed) as the FW seed too
 if [[ ( -z ${seed:+"empty"} ) || ( ${seed} == ${TESTNAME} ) ]]; then
     seed=${PLAYBOOK_RANDOM_SEED}
 fi
+# Finally -sigh- print an error if we can't get a seed by now
 if [[ -z ${seed:+"empty"} ]]; then
     echo "Failed to populate the randomization seed during FW build!"
     exit 1
