Merged PR 91358: Promote Pipeline file list check stage
Add stage to regenerate file lists and confirm the committed vf files are up to date

Related work items: #421642

diff --git a/etc/pipelines/promote-pipeline.yml b/etc/pipelines/promote-pipeline.yml
--- a/etc/pipelines/promote-pipeline.yml
+++ b/etc/pipelines/promote-pipeline.yml
@@ -57,5 +57,61 @@ stages:
       - configspec_name: 'integration_lib'
       - dut: 'caliptra_top_tb'
       - timeout: 10
-    
+
     top_repo: ''
+
+    additional_test_steps:
+      - file_list_check:
+        - display_name: 'FILE LIST CHECK'
+        - enabled: true
+        - run_in_workspace: True
+        - timeout: 60
+        - commands:
+            - 'set -e'
+            - 'cd \$AHA_POC_REPO'
+
+            # Run the Filelist generator script
+            - 'bash \$AHA_POC_REPO/tools/scripts/gen_pb_file_lists.sh'
+
+            # Check for any file changes
+            - 'if [[ \$(git status -s --untracked-files=all --ignored=traditional | wc -l) -gt 0 ]]; then
+                 echo \"Regenerating VF file lists produced some file changes:\";
+                 git status -s --untracked-files=all --ignored=traditional;
+                 git diff;
+                 echo \"*****************************************\";
+                 echo \"Review above changes locally and resubmit pipeline\";
+                 echo \"(Hint: Check \$AHA_POC_REPO for the above changes)\";
+                 echo \"*****************************************\";
+                 exit 1;
+               fi'
+      - html_doc_check:
+        - display_name: 'HTML DOC CHECK'
+        - enabled: true
+        - run_in_workspace: True
+        - timeout: 5
+        - commands:
+            - 'set -e'
+            - 'module load tools/python/python3/3.9.2'
+            - 'cd \$AHA_POC_REPO'
+
+            # Run the HTML Doc generator script
+            - 'bash \$AHA_POC_REPO/tools/scripts/reg_doc_gen.sh'
+
+            # Timestamp is always updated in index.html, resulting in 3 line changes, so ignore it
+            # Cleanup repo by clobbering the timestamp changes to index.html
+            - 'if [[ \$(git diff --numstat -- \$AHA_POC_REPO/src/integration/docs/caliptra_reg_html/index.html | sed \"s/^\(\w\+\).*/\1/\") -eq 3 ]]; then
+                 echo \"index.html has only 3 changes after regeneration, which means only the timestamp was updated. Reverting changes.\";
+                 git restore \$AHA_POC_REPO/src/integration/docs/caliptra_reg_html/index.html;
+               fi'
+
+            # Check for any file changes
+            - 'if [[ \$(git status -s --untracked-files=all --ignored=traditional | wc -l) -gt 0 ]]; then
+                 echo \"Regenerating HTML Reg documentation produced some file changes:\";
+                 git status -s --untracked-files=all --ignored=traditional;
+                 git diff;
+                 echo \"*****************************************\";
+                 echo \"Review above changes locally and resubmit pipeline\";
+                 echo \"(Hint: Check \$AHA_POC_REPO for the above changes)\";
+                 echo \"*****************************************\";
+                 exit 1;
+               fi'
