Run (protected) git fetch from origin/fork repo

diff --git a/.github/workflows/pre-run-check.yml b/.github/workflows/pre-run-check.yml
--- a/.github/workflows/pre-run-check.yml
+++ b/.github/workflows/pre-run-check.yml
@@ -55,12 +55,21 @@ jobs:
                 exit 0
               fi
             done
+            echo "git fetch origin"
+            if ! git fetch origin; then
+              echo "git fetch failed\!"
+              exit 1
+            fi
             if [[ "${SOURCE_FORK}" == "true" ]]; then
               echo "pull request is from a fork: ${SOURCE_FORK}"
               echo "fork repository owner is ${SOURCE_OWN}"
               echo "adding remote '${SOURCE_OWN}' at url '${SOURCE_URL}'"
               git remote add -f ${SOURCE_OWN} ${SOURCE_URL}
-              git fetch ${SOURCE_OWN}
+              echo "git fetch ${SOURCE_OWN}"
+              if ! git fetch ${SOURCE_OWN; then
+                echo "git fetch failed\!"
+                exit 1
+              fi
             fi
             echo "target ref for [origin/${TARGET_BR}] is $(git log -n1 --pretty=tformat:'%H' origin/${TARGET_BR} 2> /dev/null)"
             echo "source ref for [${SOURCE_OWN}/${SOURCE_BR}] is $(git log -n1 --pretty=tformat:'%H' ${SOURCE_OWN}/${SOURCE_BR} 2> /dev/null)"
@@ -257,6 +266,11 @@ jobs:
             SOURCE_URL:  ${{ github.event.pull_request.head.repo.clone_url }}
             TARGET_BR:   ${{ github.event.pull_request.base.ref }}
         run: |
+          echo "git fetch origin"
+          if ! git fetch origin; then
+            echo "git fetch failed\!"
+            exit 1
+          fi
           if [[ "${SOURCE_FORK}" == "true" ]]; then
             echo "pull request is from a fork: ${SOURCE_FORK}"
             echo "fork repository owner is ${SOURCE_OWN}"
