Timestamp job supports more flexible target branch values

diff --git a/.github/workflows/pre-run-check.yml b/.github/workflows/pre-run-check.yml
--- a/.github/workflows/pre-run-check.yml
+++ b/.github/workflows/pre-run-check.yml
@@ -117,6 +117,8 @@ jobs:
             echo -e ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
 
       - name: Check Timestamp
+        env:
+            TARGET_BR: ${{ (github.event_name == 'pull_request' && github.base_ref) || (github.event_name == 'workflow_dispatch' && inputs.base_ref) }}
         run: |
             # Find the last commit that modified any design file (not documentation)
             # Start the search with the second parent of the PR merge commit
@@ -126,12 +128,12 @@ jobs:
                 last_commit="$(git rev-parse ${last_commit}^)"
             done
             echo "Latest non-doc hash is ${last_commit}"
-            # If the last non-doc commit is already contained in branch 'main', then skip the
+            # If the last non-doc commit is already contained in branch 'TARGET_BR', then skip the
             # timestamp check -- as that commit would already be signed off through another PR.
-            # Otherwise, that commit would fail because it's part of a commit that was squashed into main
+            # Otherwise, that commit would fail because it's part of a commit that was squashed into TARGET_BR
             # much later than the original stamp commit.
-            if [[ $(git branch --remotes --list 'origin/main' --contains ${last_commit}) =~ 'origin/main' ]]; then
-                echo "Commit ${last_commit} is contained in branch 'main', skipping timestamp check"
+            if [[ $(git branch --remotes --list 'origin/$TARGET_BR' --contains ${last_commit}) =~ 'origin/$TARGET_BR' ]]; then
+                echo "Commit ${last_commit} is contained in branch '$TARGET_BR', skipping timestamp check"
             else
                 # Compare the timestamp from the latest commit with the pr_timestamp file
                 timestamp_exp=$(bc <<< "$(git log -n1 --pretty=tformat:'%ct' ${last_commit})-3600")
