Use a correct remote reference for both fork/non-fork cases

diff --git a/.github/workflows/pre-run-check.yml b/.github/workflows/pre-run-check.yml
--- a/.github/workflows/pre-run-check.yml
+++ b/.github/workflows/pre-run-check.yml
@@ -47,7 +47,6 @@ jobs:
             SOURCE_URL:  ${{ github.event.pull_request.head.repo.clone_url }}
             TARGET_BR:   ${{ github.event.pull_request.base.ref }}
         run: |
-            echo "Comparing $SOURCE_OWN/$SOURCE_BR against merge target origin/$TARGET_BR to look for compile.yml"
             local_msft_actors=${{ env.MSFT_ACTORS }}
             for msft_actor in "${local_msft_actors[@]}"; do
               if [[ "${PR_OPENER}" == "${msft_actor}" ]]; then
@@ -65,21 +64,19 @@ jobs:
               echo "fork repository owner is ${SOURCE_OWN}"
               echo "adding remote '${SOURCE_OWN}' at url '${SOURCE_URL}'"
               git remote add -f ${SOURCE_OWN} ${SOURCE_URL}
-              echo "git fetch ${SOURCE_OWN} $SOURCE_BR"
-              if ! git fetch ${SOURCE_OWN} $SOURCE_BR; then
-                echo "git fetch failed\!"
-                exit 1
-              fi
+              SOURCE_REMOTE=${SOURCE_OWN}
             else
-              echo "git fetch origin $SOURCE_BR"
-              if ! git fetch origin $SOURCE_BR; then
-                echo "git fetch failed\!"
-                exit 1
-              fi
+              SOURCE_REMOTE=origin
+            fi
+            echo "git fetch ${SOURCE_REMOTE} $SOURCE_BR"
+            if ! git fetch ${SOURCE_REMOTE} $SOURCE_BR; then
+              echo "git fetch failed\!"
+              exit 1
             fi
             echo "target ref for [origin/${TARGET_BR}] is $(git log -n1 --pretty=tformat:'%H' origin/${TARGET_BR} 2> /dev/null)"
-            echo "source ref for [${SOURCE_OWN}/${SOURCE_BR}] is $(git log -n1 --pretty=tformat:'%H' ${SOURCE_OWN}/${SOURCE_BR} 2> /dev/null)"
-            compiles=$(git diff --name-only $(git log -n1 --pretty=tformat:'%H' "origin/$TARGET_BR")...$(git log -n1 --pretty=tformat:'%H' "${SOURCE_OWN}/${SOURCE_BR}"))
+            echo "source ref for [${SOURCE_REMOTE}/${SOURCE_BR}] is $(git log -n1 --pretty=tformat:'%H' ${SOURCE_REMOTE}/${SOURCE_BR} 2> /dev/null)"
+            echo "Comparing $SOURCE_REMOTE/$SOURCE_BR against merge target origin/$TARGET_BR to look for compile.yml"
+            compiles=$(git diff --name-only $(git log -n1 --pretty=tformat:'%H' "origin/$TARGET_BR")...$(git log -n1 --pretty=tformat:'%H' "${SOURCE_REMOTE}/${SOURCE_BR}"))
             if [[ $(grep -c compile.yml <<< "$compiles") -gt 0 ]]; then
                 echo "compile.yml should not be modified for pull requests! Found:"
                 echo "$compiles"
@@ -282,21 +279,18 @@ jobs:
             echo "fork repository owner is ${SOURCE_OWN}"
             echo "adding remote '${SOURCE_OWN}' at url '${SOURCE_URL}'"
             git remote add -f ${SOURCE_OWN} ${SOURCE_URL}
-            echo "git fetch ${SOURCE_OWN} $SOURCE_BR"
-            if ! git fetch ${SOURCE_OWN} $SOURCE_BR; then
-              echo "git fetch failed\!"
-              exit 1
-            fi
+            SOURCE_REMOTE=${SOURCE_OWN}
           else
-            echo "git fetch origin $SOURCE_BR"
-            if ! git fetch origin $SOURCE_BR; then
-              echo "git fetch failed\!"
-              exit 1
-            fi
+            SOURCE_REMOTE=origin
+          fi
+          echo "git fetch ${SOURCE_REMOTE} $SOURCE_BR"
+          if ! git fetch ${SOURCE_REMOTE} $SOURCE_BR; then
+            echo "git fetch failed\!"
+            exit 1
           fi
           echo "target ref for [origin/${TARGET_BR}] is $(git log -n1 --pretty=tformat:'%H' origin/${TARGET_BR} 2> /dev/null)"
-          echo "source ref for [${SOURCE_OWN}/${SOURCE_BR}] is $(git log -n1 --pretty=tformat:'%H' ${SOURCE_OWN}/${SOURCE_BR} 2> /dev/null)"
-          mods=$(git diff --name-only $(git log -n1 --pretty=tformat:'%H' "origin/${TARGET_BR}")...$(git log -n1 --pretty=tformat:'%H' "${SOURCE_OWN}/${SOURCE_BR}"))
+          echo "source ref for [${SOURCE_REMOTE}/${SOURCE_BR}] is $(git log -n1 --pretty=tformat:'%H' ${SOURCE_REMOTE}/${SOURCE_BR} 2> /dev/null)"
+          mods=$(git diff --name-only $(git log -n1 --pretty=tformat:'%H' "origin/${TARGET_BR}")...$(git log -n1 --pretty=tformat:'%H' "${SOURCE_REMOTE}/${SOURCE_BR}"))
           if [[ $(IFS='\n' grep -c -v '\.md\|\.png' <<< "$mods") -gt 0 ]]; then
             echo "Found modified source files in ${SOURCE_BR}"
             echo "src_mods=true" >> "${GITHUB_OUTPUT}"
