Consolidate hashing code; add informative prints

diff --git a/.github/workflows/pre-run-check.yml b/.github/workflows/pre-run-check.yml
--- a/.github/workflows/pre-run-check.yml
+++ b/.github/workflows/pre-run-check.yml
@@ -29,6 +29,7 @@ jobs:
             SOURCE_BR: ${{ github.head_ref }}
             TARGET_BR: ${{ github.base_ref }}
         run: |
+            echo "Comparing $SOURCE_BR against merge target $TARGET_BR to look for compile.yml"
             compiles=$(git diff --name-only origin/$TARGET_BR...origin/$SOURCE_BR)
             if [[ $(echo "$compiles" | grep -c compile.yml) -gt 0 ]]; then
                 echo "compile.yml should not be modified for pull requests! Found:"
@@ -52,17 +53,12 @@ jobs:
                                           -o -name "*.vh" \
                                           -o -name "*.c" \
                                           -o -name "*.h" \
-                                          -o -name "pr_timestamp" | sort | tee $GITHUB_WORKSPACE/file_list.txt
-            sed -i "s,^$GITHUB_WORKSPACE/,," $GITHUB_WORKSPACE/file_list.txt
-      - name: Run File Hash
-        run: |
-            hash=$($GITHUB_WORKSPACE/.github/scripts/rtl_hash.sh $GITHUB_WORKSPACE $GITHUB_WORKSPACE/file_list.txt)
-            if [[ -z ${hash:+"empty"} ]]; then
-                echo "Failed to run hash script"
-                echo $hash
-                exit 1;
-            fi
-            echo "RTL hash is $result"
+                                          -o -name "pr_timestamp" | sort > $GITHUB_WORKSPACE/.github/workflow_metadata/file_list.txt
+            sed -i "s,^$GITHUB_WORKSPACE/,," $GITHUB_WORKSPACE/.github/workflow_metadata/file_list.txt
+            echo "Found $(wc -l $GITHUB_WORKSPACE/.github/workflow_metadata/file_list.txt) source code files to hash"
+            echo -e "First five files:\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
+            head -5 $GITHUB_WORKSPACE/.github/workflow_metadata/file_list.txt
+            echo -e ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
       - name: Check Timestamp
         run: |
             timestamp_exp=$(bc <<< "$(git log -n1 --pretty=tformat:'%ct')-3600")
@@ -70,22 +66,31 @@ jobs:
                 echo "Error, file not found: $GITHUB_WORKSPACE/.github/workflow_metadata/pr_timestamp"
                 exit 1
             fi
-            timestamp=$(tail -1 $GITHUB_WORKSPACE/.github/workflow_metadata/pr_hash)
+            timestamp=$(tail -1 $GITHUB_WORKSPACE/.github/workflow_metadata/pr_timestamp)
             if [[ ${timestamp} -lt ${timestamp_exp} ]]; then
                 echo "Error, submitted timestamp [${timestamp}] is outdated: it precedes the latest commit to branch by more than an hour [${timestamp_exp}]"
                 exit 1
             fi
+            echo "Submitted timestamp [${timestamp}] meets the recency requirement: [${timestamp_exp}]"
       - name: Check Hash
         run: |
+            hash=$($GITHUB_WORKSPACE/.github/scripts/rtl_hash.sh $GITHUB_WORKSPACE $GITHUB_WORKSPACE/.github/workflow_metadata/file_list.txt)
+            if [[ -z ${hash:+"empty"} ]]; then
+                echo "Failed to run hash script"
+                echo $hash
+                exit 1;
+            fi
+            echo "RTL hash is $hash"
             if [[ ! -f $GITHUB_WORKSPACE/.github/workflow_metadata/pr_hash ]]; then
                 echo "Error, file not found: $GITHUB_WORKSPACE/.github/workflow_metadata/pr_hash"
                 exit 1
             fi
-            hash_orig=$(tail -1 ${hash_file_org})
+            hash_orig=$(tail -1 $GITHUB_WORKSPACE/.github/workflow_metadata/pr_hash)
             if [[ ${hash_orig} != ${hash} ]]; then
                 echo "Error, submitted hash [${hash_orig}] does not match calculated hash [${hash}]"
                 exit 1
             fi
+            echo "Submitted hash [${hash_orig}] matches the calculated hash: [${hash}]"
 
   # Check License Headers
   # Check for microsoft employee or that all compile.yml/.vf are untouched
